### ISSUE TITLE
platform does not load - permission denied

### ISSUE THREAD

**Issue by mastermarkush** [epenet/hassRenaultZE#17]
Hi! Sorry to bother you, however I have an issue which I have both on version 0.89.2 and the latest release v0.99.3 (a brand new install within a FreeNas jail, in a virtual environment). I follow your installation guide, but the platform does not load when homeassistant starts. Here's the error message I get in the logs.

Error while setting up platform renaultze

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/home/hass/homeassistant/custom_components/renaultze/sensor.py", line 68, in async_setup_platform
    g = Gigya(api_key=g_key,root_url=g_url)
  File "/srv/homeassistant/lib/python3.6/site-packages/pyze/api/gigya.py", line 23, in __init__
    self.set_api_key(api_key)
  File "/srv/homeassistant/lib/python3.6/site-packages/pyze/api/gigya.py", line 26, in set_api_key
    self._credentials.store('gigya-api-key', api_key, None)
  File "/srv/homeassistant/lib/python3.6/site-packages/pyze/api/credentials.py", line 70, in store
    self._write()
  File "/srv/homeassistant/lib/python3.6/site-packages/pyze/api/credentials.py", line 75, in _write
    os.makedirs(dirname)
  File "/srv/homeassistant/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.credentials'

Is there a way that you could help me out? Many thanks!!! Markus

**Comment by epenet** [comment]
Hi Markus,

It looks like the issue comes from the way the [pyze](https://github.com/jamesremuscat/pyze) module caches the credentials.
By default, this is "os.path.expanduser('~/.credentials/pyze.json')".
Can you try to create the corresponding folder and give access to your user?

If that doesn't work, then maybe you need to request changes on the pyze module...

**Comment by epenet** [comment]
Ref https://github.com/jamesremuscat/pyze/issues/10

**Comment by epenet** [comment]
Hi @mastermarkush,

Can you update to [v3.0.0](https://github.com/epenet/hassRenaultZE/releases/tag/v3.0.0) and see if that is still an issue?

**Comment by epenet** [comment]
OP went away.
