### ISSUE TITLE
Cannot update sensor

### ISSUE THREAD

**Issue by jugla** [epenet/hassRenaultZE#47]
I have install hassRenaultZE, in order to monitor my Zoe .
In the home assistant log, I have the following traceback 
`
2020-09-24 21:35:54 WARNING (SyncWorker_9) [custom_components.renaultze.sensor] Battery update failed: Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/renaultze/sensor.py", line 252, in update
    jsonresult = self._vehicle.battery_status()
  File "/srv/homeassistant/lib/python3.7/site-packages/pyze/api/kamereon.py", line 193, in battery_status
    return self._get('battery-status', 2)
  File "/srv/homeassistant/lib/python3.7/site-packages/pyze/api/kamereon.py", line 166, in _get
    response.raise_for_status()
  File "/srv/homeassistant/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/abcd1234
/kamereon/kca/car-adapter/v2/cars/VF1AG000262186006/battery-status?country=GB
`

The sensor is always in "unknown state".

How can I get the hassRenaultZE working

**Comment by epenet** [comment]
Does your account work correctly inside the Android app?

**Comment by jugla** [comment]
Yes, it works within "MyRenault"
(French version)

**Comment by epenet** [comment]
Also, you can try to enable full PyZe debug:

```yaml
logger:
  default: warn
  logs:
    custom_components.renaultze.sensor: debug
    pyze: debug
```

**Comment by jugla** [comment]
I 've the PyZE CLI. It works !

**Comment by jugla** [comment]
The pyze CLI put a warning, since in my case, there are 2 Kamereon accounts "Multiple Kamereon accounts found:".
In configuration.yaml, I set up Kamereon account with the first account 
`k_account_id: xxxxxxx`
xxxxx is the number given back by pyze CLI.

It solves my issue.

NB : My ZOE car is a second-hand car. I think it explains.
